### ISSUE TITLE
Does not handle error 404s

### ISSUE THREAD

**Issue by Rich700000000000** [Lacsap-/tumblr2pc#3]
Hey, I was running this and the _tumblr_ downloaded fine, but the other sites:

```
[generic] 56f3eee8c375551c00ee45d9: Requesting header
WARNING: Could not send HEAD request to https://www.wedgies.com/question/56f3eee8c375551c00ee45d9: HTTP Error 404: Not Found
[generic] 56f3eee8c375551c00ee45d9: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 56f3eee8c375551c00ee45d9: Extracting information
ERROR: Unsupported URL: https://www.wedgies.com/question/56f3eee8c375551c00ee45d9
Traceback (most recent call last):
  File "tumblr2pc.py", line 287, in <module>
    main()
  File "tumblr2pc.py", line 273, in main
    likes_or_posts)
  File "tumblr2pc.py", line 159, in get_video
    ydl.download([i["permalink_url"]])
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1677, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 680, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 540, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 510, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unsupported URL: https://www.wedgies.com/question/56f3eee8c375551c00ee45d9
```

It can just skip those, right?

**Comment by pboardman** [comment]
To be honest tumblr2pc is a bit broken and it need to be fixed. There is almost no error handling so everytime you get a 404 the whole thing just crash. it's been a while since I played with it but I'll try fixing it when I get some time.

**Comment by pboardman** [comment]
I added some try/except with should hopefully solve this problem.
